#!/usr/bin/env python3
"""Generate the radar's town underlay data from GeoNames.

The radar only ever draws towns within its widest range (30 mi), so shipping a
worldwide gazetteer would be wasted flash — a few hundred places around the
radar center is enough and costs a handful of KB. The committed header therefore
covers one region; regenerate it for yours:

    python tools/generate_towns.py --center 40.13,-105.18 --radius-km 400
    python tools/generate_towns.py --min-pop 5000        # sparser labels

With no --center it uses config::kFactoryLatitude / kFactoryLongitude from
include/config.h. Places outside the extract simply do not draw, so a radar
center far from it shows an empty underlay rather than misbehaving.

Source: https://download.geonames.org/export/dump/ (CC BY 4.0). cities1000 is
~10 MB and is cached next to this script as cities1000.txt.
"""
from __future__ import annotations

import argparse
import io
import math
import re
import sys
import urllib.request
import zipfile
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
CACHE = Path(__file__).resolve().parent / "cities1000.txt"
ZIP_URL = "https://download.geonames.org/export/dump/cities1000.zip"
OUT = ROOT / "include" / "data" / "towns_lookup.h"
NAME_CAP = 24  # inline char[NAME_CAP], truncated with care below


def factory_center() -> tuple[float, float]:
    src = (ROOT / "include" / "config.h").read_text(encoding="utf-8")
    lat = re.search(r"kFactoryLatitude\s*=\s*(-?[\d.]+)", src)
    lon = re.search(r"kFactoryLongitude\s*=\s*(-?[\d.]+)", src)
    if not lat or not lon:
        sys.exit("could not read kFactoryLatitude/kFactoryLongitude from include/config.h")
    return float(lat.group(1)), float(lon.group(1))


def load_gazetteer() -> list[str]:
    if CACHE.exists():
        print(f"using cached {CACHE.name}")
        return CACHE.read_text(encoding="utf-8").splitlines()
    print(f"downloading {ZIP_URL} ...")
    raw = urllib.request.urlopen(ZIP_URL, timeout=300).read()
    text = zipfile.ZipFile(io.BytesIO(raw)).read("cities1000.txt").decode("utf-8")
    CACHE.write_text(text, encoding="utf-8")
    print(f"cached {len(raw)/1e6:.1f} MB -> {CACHE.name}")
    return text.splitlines()


def km_between(lat_a: float, lon_a: float, lat_b: float, lon_b: float) -> float:
    """Flat-earth distance; plenty for a few-hundred-km extract."""
    return math.hypot((lat_b - lat_a) * 111.32,
                      (lon_b - lon_a) * 111.32 * math.cos(math.radians(lat_a)))


def ascii_name(raw: str) -> str:
    """The 4pt font is 7-bit ASCII, so drop anything it cannot draw."""
    cleaned = "".join(c for c in raw if 32 <= ord(c) < 127).strip()
    return cleaned[: NAME_CAP - 1]


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--center", help="LAT,LON (default: config.h factory center)")
    ap.add_argument("--radius-km", type=float, default=400.0)
    ap.add_argument("--min-pop", type=int, default=1000)
    ap.add_argument("--max", type=int, default=1200, help="cap on emitted places")
    ap.add_argument("--out", type=Path, default=OUT)
    args = ap.parse_args()

    if args.center:
        lat_s, lon_s = args.center.split(",")
        center = (float(lat_s), float(lon_s))
    else:
        center = factory_center()
    print(f"center {center[0]:.5f},{center[1]:.5f}  radius {args.radius_km:.0f} km  "
          f"min pop {args.min_pop}")

    places: list[tuple[int, str, float, float]] = []
    for row in load_gazetteer():
        f = row.split("\t")
        if len(f) < 15:
            continue
        try:
            lat, lon, pop = float(f[4]), float(f[5]), int(f[14] or 0)
        except ValueError:
            continue
        if pop < args.min_pop:
            continue
        if km_between(center[0], center[1], lat, lon) > args.radius_km:
            continue
        name = ascii_name(f[2] or f[1])
        if name:
            places.append((pop, name, lat, lon))

    # Population order: the renderer places labels most-populous first and drops
    # any that would collide, so the important towns win the space.
    places.sort(key=lambda p: (-p[0], p[1]))
    places = places[: args.max]
    if not places:
        sys.exit("no places matched — widen --radius-km or lower --min-pop")

    lines = [
        "#pragma once",
        "// Auto-generated by tools/generate_towns.py — do not edit.",
        f"// {len(places)} places within {args.radius_km:.0f} km of "
        f"{center[0]:.5f},{center[1]:.5f} (population >= {args.min_pop}).",
        "// Source: GeoNames cities1000 (https://www.geonames.org/, CC BY 4.0).",
        "// Ordered by population descending: label placement takes them in order.",
        "",
        "#include <cstddef>",
        "#include <cstdint>",
        "",
        "namespace data::towns {",
        "",
        f"constexpr size_t kCount = {len(places)};",
        f"constexpr int kNameCap = {NAME_CAP};",
        "",
        "struct Town {",
        "  char name[kNameCap];",
        "  float lat;",
        "  float lon;",
        "  uint32_t population;",
        "};",
        "",
        "constexpr Town kTowns[kCount] = {",
    ]
    for pop, name, lat, lon in places:
        lines.append(f'    {{"{name}", {lat:.5f}f, {lon:.5f}f, {pop}}},')
    lines += ["};", "", "}  // namespace data::towns", ""]

    args.out.write_text("\n".join(lines), encoding="utf-8")
    approx = len(places) * (NAME_CAP + 12)
    print(f"wrote {args.out.relative_to(ROOT)} — {len(places)} places, ~{approx/1024:.1f} KB")
    print("largest:", ", ".join(n for _, n, _, _ in places[:6]))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
